### ISSUE TITLE
Not able to pip install

### ISSUE THREAD

**Issue by satrajitgithub** [Svdvoort/prognosais#152]
Hi @Svdvoort ,

I am not able to install prognosais using:
`pip install prognosais==0.2.7`
and keep getting this error:
`ERROR: Could not find a version that satisfies the requirement prognosais==0.2.7 (from versions: none)
ERROR: No matching distribution found for prognosais==0.2.7`

Can you please help?

**Comment by Svdvoort** [comment]
Which version of `python` and `pip` are you using? Could you share the output of `python --version` and `pip --version`? prognosais is only supported in python3, so if you are using python 2 it will not found a installable package

**Comment by satrajitgithub** [comment]
I am using `python 3.6.2` and `pip 21.1.3`. I am trying to do this on Windows7. Is this not compatible with windows?

**Comment by Svdvoort** [comment]
There are indeed no packages for Windows - only for Linux. Getting GPU support to properly work on windows is flaky, and I don't have a windows environment to develop and test this on, so windows support will not be added.
